export const CREATE_PROJECT = "CREATE_PROJECT";
export const GET_PROJECT_ALL = "GET_PROJECT_ALL";
export const GET_PROJECT = "GET_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const CREATE_PROJECT_DATABASE = "CREATE_PROJECT_DATABASE";

export const CREATE_LANGUAGE = "CREATE_LANGUAGE";
export const GET_LANGUAGE_ALL = "GET_PROJLANGUAGE_ALL";
export const GET_LANGUAGE = "GET_LANGUAGE";
export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";
export const DELETE_LANGUAGE = "DELETE_LANGUAGE";

export const CREATE_COUNTRY = "CREATE_COUNTRY";
export const GET_COUNTRY_ALL = "GET_COUNTRY_ALL";
export const GET_COUNTRY = "GET_COUNTRY";
export const UPDATE_COUNTRY = "UPDATE_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const CURRENT_USER = "CURRENT_USER";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_IMAGE_SERIES_NUMBER = "GET_IMAGE_SERIES_NUMBER";
export const GET_IMAGE_DATA = "GET_IMAGE_DATA";
export const UPDATE_IMAGE_COMMENT = "UPDATE_IMAGE_COMMENT";
export const IMAGE_DATA_INSERT = "IMAGE_DATA_INSERT";
